### PR TITLE
Adds apple pay support for FirstData E4

### PR DESCRIPTION
**Pull request by jnormore**
Another continuation of https://github.com/Shopify/active_merchant/pull/1566 for FirstData E4.

There's no way to test this without doing a live test (they don't have sandbox verification for it). I definite confirmation from FirstData that this is the format they expect this data in and that it will work without issue.

This can be merged as soon as https://github.com/Shopify/active_merchant/pull/1566 in in.

@girasquid @bizla for review please, thanks!

cc @markabe @rwdaigle @ntalbott

### CODE REVIEW

**Comment by bizla** [comment]
:+1:

**Comment by girasquid** [comment]
:+1:

**Comment by rwdaigle** [comment]
@jnormore is there a reason why this is still in the `network-tokenization` branch and not `master` (with the other Apple Pay supporting gateways)?

**Comment by jnormore** [comment]
that was a mistake, should have merged to master :/

**Comment by jnormore** [comment]
fixed, merged to master

**Pull request merged**
