### PR TITLE
PaystationGateway purchase update

### PR DESCRIPTION
**Pull request by Paystation**
Paystation 2-party purchase implementation
Please contact info@paystation.co.nz for queries

### CODE REVIEW

**Comment by ntalbott** [comment]
Whitespace is all wonky in your patch - can you please fix?

**Comment by Paystation** [comment]
Hi Nathaniel

 

This has been fixed :)

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Comment by ntalbott** [comment]
@Paystation this seems like a huge regression. What's the purpose of this patch?

**Comment by Paystation** [comment]
Hey Nathaniel

 

We were requested to fix the whitespace, which is the purpose of this patch, if I have interpreted your question correctly?

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Comment by ntalbott** [comment]
@Paystation sorry, should have been clearer - what is the purpose for the Pull Request as a whole? Now that the whitespace is fixed I'm reading it and it seems like a regression in functionality, and doesn't follow the ActiveMerchant project's coding standards or conventions.

**Comment by Paystation** [comment]
Hey Nathaniel

 

We are a Payment Gateway and the Pull Request is supposed to be a direct integration with Shopify.  Just checking to ensure you are referring to this pull request - https://github.com/Shopify/active_merchant/pull/1577 as the developer had originally submitted the PR into the incorrect repository (https://github.com/Shopify/offsite_payments/pull/76).

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Comment by ntalbott** [comment]
@Paystation there's already an existing adapter in ActiveMerchant: https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/paystation.rb

This Pull Request modifies that adapter in an... unhelpful way.

So far as I can tell this Pull Request is not needed, and you should just talk to Shopify directly about having them enable the existing adapter.

**Comment by Paystation** [comment]
Thanks Nathaniel, that adapter was not written by a Paystation developer but we will look into it.  Do you know where we would be able to find the ActiveMerchant project’s coding standards and conventions?  It would be really helpful for our developer :)

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Comment by ntalbott** [comment]
The CONTRIBUTING file is of course critical: https://github.com/Shopify/active_merchant/blob/master/CONTRIBUTING.md

Also, it's important to check out how the other gateway adapters are implemented, as well as the default template used when a new gateway is generated.

**Comment by Paystation** [comment]
Great!  Thanks Nathaniel for your help

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Comment by ntalbott** [comment]
OK, going to close this PR for now; feel free to open a new one if you decide the adapter needs work. FWIW the one that's already here in ActiveMerchant seems pretty solid, so I wouldn't think it'd need work unless there's specific functionality you think should be added to it.

**Comment by Paystation** [comment]
Hey Nathaniel

 

We have modified the existing adapter and the updated PR can be found here https://github.com/Shopify/active_merchant/pull/1592 

 



Best Regards,

Karl Gerrie


Account Manager


ddi

+64 4 917 8085


email

 <mailto:karl@paystation.co.nz> karl@paystation.co.nz 





postal

po box 12082, Wellington 6144

fax

+64 4 917 8099


phone

+64 4 917 8097

email

 <mailto:info@paystation.co.nz> info@paystation.co.nz

Follow us on Twitter for service status updates:  <http://www.twitter.com/PaystationNZ> PaystationNZ

**Pull request closed without merging**
