### PR TITLE
Cenpos

### PR DESCRIPTION
**Pull request by markabe**
@ntalbott Please review.

### CODE REVIEW

**Comment by markabe** [comment]
Might as well flag you too @duff :smile:

**Comment by duff** [comment]
Does CenPOS offer any avs_response and/or cvv_response information?

**Comment by markabe** [comment]
There did appear to be some information in the response.  However I tried to altering the requests in order to affect the response and it always came back Match.  I didn't have much confidence that it did what it should so I left it out.

**Comment by duff** [comment]
I don't see much info at all in their docs about it either. :(

**Comment by duff** [comment]
Closed by 94b7645fe93446fde3173de1e0f5a28dc25d31d6.

**Pull request closed without merging**
