### PR TITLE
[fix] WorldpayOnlinePayments - Description can't be null

### PR DESCRIPTION
**Pull request by ao**

### CODE REVIEW

**Comment by andrewpaliga** [comment]
@ao this change looks good but we're still getting an error in our remote tests. Refund method needs to support passing in an amount as a parameter. When I switch `nil` to `@amount` [in the remote refund test](https://github.com/Shopify/active_merchant/blob/master/test/remote/gateways/remote_worldpay_online_payments_test.rb#L69) I get an error.

**Comment by ao** [comment]
@andrewpaliga right now our API processes a full refund if a refundAmount is not set or is set to `0` (hence `nil`). Otherwise it attempts to process the refund as a `partialRefund`.
Therefore it is attempting to process a `partialRefund` of the total amount, which is not partial. That is why it fails.

Is it possible to move forward with this implementation without the API changes as they may take some time to get to production?

**Comment by andrewpaliga** [comment]
@ao unfortunately we cannot move forward with Shopify integration without API changes as all full refunds will fail with the current implementation.

**Comment by ao** [comment]
@andrewpaliga API has been updated and have amended the relevant test.

**Comment by andrewpaliga** [comment]
@ao :+1:

**Pull request merged**
