### PR TITLE
Implement transaction scrubbing for Authorize.Net

### PR DESCRIPTION
**Pull request by girasquid**
@duff @j-mutter for review.

I'd like some feedback on what to leave inside the remote tests - right now I just have the commented out `dump_transcript_and_fail` because I'd like it to be easy to regenerate a transcript when you need one, but I'm open to suggestions.

### CODE REVIEW

**Comment by j-mutter** [comment]
Code looks good.

For the transcript dump, could we make it a rake task or something maybe?

**Comment by girasquid** [comment]
I did some checking into making a rake task, and it turned out to be pretty non-trivial. For now I think I'm just going to stick to having it live in the remote tests, which already have the right credentials + options for the call.

**Comment by j-mutter** [comment]
okay.jpg

**Comment by girasquid** [comment]
I merged this but forgot to update the commit message - closing.

**Pull request closed without merging**
