### PR TITLE
Add IPP gateway: IPPay

### PR DESCRIPTION
**Pull request by jomit427**
Hello,

I represent IPPay and we are currently boarding GAW Miners onto our gateway.  They have used Shopify as their billing service and mentioned they would like to continue using Shopify.  They are temporarily using Auth.net via our gateway and have requested that we look into a direct integration with Shopify.  Is there a good time we could get in contact and discuss this integration?  I'll keep an eye on the pull request here but you can also shoot me an email at jmitchell@converge-tech.com or give me a call at 1-847-346-0990.

### CODE REVIEW

**Comment by andrewpaliga** [comment]
@jomit427 we are looking to add beta IPP integration to Shopify soon. Please email payment-integrations@shopify.com for further inquires.

**Comment by jomit427** [comment]
We are actually a different gateway.  I represent Convergence Technologies and our company name is IPPay, though I can see where the confusion stems from.  Like I said we’ve just boarded GAW Miners onto our gateway and they really like your service and would like to keep using you guys.  You can check out our website at www.ippay.com<http://www.ippay.com>.

Let me know if there’s any information I can provide for you guys.  Thank you.

Joshua Mitchell
Support Specialist


[cid:image001.jpg@01D03177.C635ACA0]<http://www.converge-tech.com/>



Where Best of Class Technologies ConVerge
ConVergence Technologies, Inc.
16W215 83rd St. Suite D
Burr Ridge, IL 60527<http://maps.google.com/maps?hl=en&ie=UTF8&q=convergence+technologies,&near=Burr+Ridge,+IL&fb=1&cid=41737923,-87940278,9511917714351008728&li=lmd&om=0&ll=41.737952,-87.940235&spn=0.042591,0.080338&z=14&iwloc=A>
tel

847-346-0990

jmitchell@converge-tech.com<mailto:jmitchell@converge-tech.com>
support@ippay.com<mailto:support@ippay.com>

**Comment by j-mutter** [comment]
Due to the confusion, I think this can be reopened?

**Comment by j-mutter** [comment]
Wait, this branch is… interesting. Looks like everything here has been merged, and is for an unrelated gateway. Closing. #caseofthemondays

**Pull request closed without merging**
