### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by wvanbergen**
Add a **CONTRIBUTING.md** file, which will be displayed when people open new issues or pull requests.
I moved some stuff from README and other files into this file.

@Shopify/payments @ntalbott do you agree with the guidelines in here?

### CODE REVIEW

**Comment by girasquid** [comment]
:+1:

**Comment by j-mutter** [comment]
:+1:

**Comment by edward** [comment]
:dragon_face: coooooooooool

**Comment by ntalbott** [comment]
This looks great. Will add things to it as they come up.

**Pull request merged**
