### PR TITLE
WorldPay: Remove country overlap with WorldPay US

### PR DESCRIPTION
**Pull request by markabe**
@ntalbott As we discussed.

### CODE REVIEW

**Comment by j-mutter** [comment]
Um, what's the reasoning for this? Does this product/endpoint not actually support US?

**Comment by ntalbott** [comment]
@j-mutter so the deal is, Worldpay has a bunch of different products, and they don't provision the product that ActiveMerchant calls "Worldpay" for US merchants. The country list is supposed to indicate where a gateway account is acquirable, not where the gateway can be used for processing, so this change (better) reflects reality.

@markabe I'd also like us to change the display name of the `Worldpay` gateway to `Worldpay Global` to help reflect this distinction.

Overall, Worldpay is a mess, and after lots of merchant confusion, this is one piece of what we're doing to try to help future merchants be less confused.

**Comment by markabe** [comment]
@ntalbott Updated display name.

**Comment by ntalbott** [comment]
@j-mutter any concerns remain before I merge? We could do this just on the Spreedly side, but our thinking was that it wasn't just an issue for our customers.

**Comment by j-mutter** [comment]
As long as it's just the display name that's changed, I think we're ok. We'll need to update some stuff on our end, but otherwise I think this is ok.  @girasquid thoughts?

**Comment by ntalbott** [comment]
@j-mutter so this is going to change the display name, and the supported countries for the `worldpay` adapter. No change to the class name and such, though - this is all metadata tweaks.

**Comment by girasquid** [comment]
> No change to the class name and such, though - this is all metadata tweaks.

In light of that, I don't think we have any issues here. Thanks for doing this!

**Pull request closed without merging**
