### PR TITLE
Add finalize option to quickpay at capture

### PR DESCRIPTION
**Pull request by askehansen**
Add the ability to finalize the transaction when doing a partial capture so the transaction doesn't remain open

http://doc.quickpay.dk/api/messagetypes.html#index6h2

### CODE REVIEW

**Comment by duff** [comment]
Hi @askehansen,

I'm thinking a unit test verifying that we're passing the right value for each of the cases would be helpful for this pull request.  Many of the gateways have unit tests using `CommStub` to assert such things.

Thanks!

**Comment by askehansen** [comment]
Im not quite sure what you mean?

**Comment by duff** [comment]
Here's an example in the Stripe unit tests verifying that the right things get passed to the gateway:

https://github.com/Shopify/active_merchant/blob/f8998d6747a9d99fc727731d4f1c9e9690001a3e/test/unit/gateways/stripe_test.rb#L506-L512

Does that help explain?

**Comment by askehansen** [comment]
Yea thanks, i'll do that

**Comment by askehansen** [comment]
I just added some tests

**Comment by duff** [comment]
Looks great @askehansen!  Just merged it.  Thanks!

**Pull request closed without merging**
