### PR TITLE
Add standard error codes for auth.net

### PR DESCRIPTION
**Pull request by andrewpaliga**
Added applicable authorize.net error codes defined [here](http://www.authorize.net/support/ReportingGuide_XML.pdf).

@j-mutter @aprofeit for review

@ntalbott

### CODE REVIEW

**Comment by aprofeit** [comment]
:+1:

**Comment by j-mutter** [comment]
Got remote test output for those?

Otherwise :hatched_chick:

**Comment by andrewpaliga** [comment]
Finished in 12.435057742 seconds.
----------------------------------------------------------------------------------------------------------------------
17 tests, 69 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------
1.37 tests/s, 5.55 assertions/s

**Comment by andrewpaliga** [comment]
```
vagrant@vagrant:~/src/active_merchant$ bundle exec rake test TEST=test/remote/gateways/remote_authorize_net_test.rb
.................................

Finished in 36.460307549 seconds.
----------------------------------------------------------------------------------------------------------------------
33 tests, 97 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------
0.91 tests/s, 2.66 assertions/s
```

**Pull request merged**
